DROP TABLE IF EXISTS games;
CREATE TABLE games (
    GAME_DATE_EST VARCHAR(10),
    GAME_ID BIGINT,
    GAME_STATUS_TEXT VARCHAR(255),
    HOME_TEAM_ID BIGINT,
    VISITOR_TEAM_ID BIGINT,
    SEASON INT,
    TEAM_ID_home BIGINT,
    PTS_home INT,
    FG_PCT_home DECIMAL(5, 4),
    FT_PCT_home DECIMAL(5, 4),
    FG3_PCT_home DECIMAL(5, 4),
    AST_home INT,
    REB_home INT,
    TEAM_ID_away BIGINT,
    PTS_away INT,
    FG_PCT_away DECIMAL(5, 4),
    FT_PCT_away DECIMAL(5, 4),
    FG3_PCT_away DECIMAL(5, 4),
    AST_away INT,
    REB_away INT,
    HOME_TEAM_WINS BOOLEAN
);

DROP TABLE IF EXISTS games_details;
CREATE TABLE games_details (
    GAME_ID BIGINT,
    TEAM_ID BIGINT,
    TEAM_ABBREVIATION VARCHAR(10),
    TEAM_CITY VARCHAR(50),
    PLAYER_ID BIGINT,
    PLAYER_NAME VARCHAR(100),
    NICKNAME VARCHAR(50),
    START_POSITION VARCHAR(5),
    COMMENT TEXT,
    MIN VARCHAR(5), 
    FGM INT,
    FGA INT,
    FG_PCT DECIMAL(5, 3),
    FG3M INT,
    FG3A INT,
    FG3_PCT DECIMAL(5, 3),
    FTM INT,
    FTA INT,
    FT_PCT DECIMAL(5, 3),
    OREB INT,
    DREB INT,
    REB INT,
    AST INT,
    STL INT,
    BLK INT,
    TOVR INT,
    PF INT,
    PTS INT,
    PLUS_MINUS INT
);

DROP TABLE IF EXISTS players;
CREATE TABLE players (
    PLAYER_NAME VARCHAR(100),
    TEAM_ID BIGINT,
    PLAYER_ID BIGINT,
    SEASON YEAR
);

DROP TABLE IF EXISTS ranking;
CREATE TABLE ranking (
    TEAM_ID BIGINT,
    LEAGUE_ID BIGINT,
    SEASON_ID INT,
    STANDINGSDATE VARCHAR(10),
    CONFERENCE VARCHAR(50),
    TEAM VARCHAR(50),
    G INT,
    W INT,
    L INT,
    W_PCT DECIMAL(5, 3),
    HOME_RECORD VARCHAR(10),
    ROAD_RECORD VARCHAR(10),
    RETURNTOPLAY VARCHAR(50)
);

DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
    LEAGUE_ID INT,
    TEAM_ID BIGINT,
    MIN_YEAR INT,
    MAX_YEAR INT,
    ABBREVIATION VARCHAR(10),
    NICKNAME VARCHAR(50),
    YEARFOUNDED INT,
    CITY VARCHAR(50),
    ARENA VARCHAR(100),
    ARENACAPACITY INT,
    TOWNER VARCHAR(100),
    GENERALMANAGER VARCHAR(100),
    HEADCOACH VARCHAR(100),
    DLEAGUEAFFILIATION VARCHAR(100)
);
